CREATE DATABASE aplikasi

USE aplikasi

CREATE TABLE Users(
	UserID CHAR(15),
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255),
	School VARCHAR(255),
	Adress VARCHAR(255),
	Email VARCHAR(255) NOT NULL,
	PhoneNumber VARCHAR(255),
	Location VARCHAR(255),
	DateofBirth DATE,
	Gender CHAR(1),

	CONSTRAINT Users_userID_PK PRIMARY KEY(UserID),
	CHECK (Gender LIKE 'M' OR Gender LIKE 'F' OR Gender LIKE 'N')
)

CREATE TABLE Posts(
	PostID CHAR(20),
	UserID CHAR(15),
	PostDate DATE NOT NULL,
	PostContent VARCHAR(255) NOT NULL,

	CONSTRAINT Posts_postID_PK PRIMARY KEY(PostID),
	CONSTRAINT Posts_userID_FK FOREIGN KEY(UserID) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE SET NULL
)

CREATE TABLE Friends(
	RelationID CHAR(20),
	UserID CHAR(15),
	FriendID CHAR(15) NOT NULL,
	
	CONSTRAINT Friends_relationID_PK PRIMARY KEY(relationID),
	CONSTRAINT Friends_userID_FK FOREIGN KEY(userID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE SET NULL
)

CREATE TABLE Pages(
	PageID CHAR(20),
	PageName VARCHAR(255) NOT NULL,
	PageContent VARCHAR(255) NOT NULL,
	
	CONSTRAINT Pages_PageID_PK PRIMARY KEY(pageID)
)

CREATE TABLE PageLikes(
	PageLikeID CHAR(20),
	PageID CHAR(20),
	UserID CHAR(15),
	PageName VARCHAR(255) NOT NULL,
	PageContent VARCHAR(255) NOT NULL,
	
	CONSTRAINT PageLikes_PageLikeID_PK PRIMARY KEY(pageLikeID),
	CONSTRAINT PageLikes_PageID_FK FOREIGN KEY(PageID) REFERENCES Pages(pageID) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT PageLikes_UserID_FK FOREIGN KEY(UserID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE SET NULL
)

CREATE TABLE PostLikes(
	PostLikeID CHAR(20),
	PostID CHAR(20),
	UserID CHAR(15) NOT NULL,
	
	CONSTRAINT PostLikes_PostLikeID_PK PRIMARY KEY(PostLikeID),
	CONSTRAINT PostLikes_PostID_FK FOREIGN KEY(PostID) REFERENCES Posts(PostID) ON UPDATE CASCADE ON DELETE SET NULL
)

CREATE TABLE Photos(
	PhotoID CHAR(20),
	PostID CHAR(20),
	ImageContent VARCHAR(255) NOT NULL,
	
	CONSTRAINT Photos_PhotoID_PK PRIMARY KEY(PhotoID),
	CONSTRAINT Photos_PostID_FK FOREIGN KEY(PostID) REFERENCES Posts(PostID) ON UPDATE CASCADE ON DELETE SET NULL
)

CREATE TABLE Shares(
	ShareID CHAR(20),
	PostID CHAR(20),
	UserID CHAR(15) NOT NULL,
	
	CONSTRAINT Shares_ShareID_PK PRIMARY KEY(ShareID),
	CONSTRAINT Shares_PostID_FK FOREIGN KEY(PostID) REFERENCES Posts(PostID) ON UPDATE CASCADE ON DELETE SET NULL
)

CREATE TABLE Comments(
	CommentID CHAR(20),
	PostID CHAR(20),
	UserID CHAR(15) NOT NULL,
	CommentDate DATE NOT NULL,
	CommentContent VARCHAR(255) NOT NULL,

	CONSTRAINT Comments_CommentID_PK PRIMARY KEY(CommentID),
	CONSTRAINT Comments_PostID_FK FOREIGN KEY(PostID) REFERENCES Posts(PostID) ON UPDATE CASCADE ON DELETE SET NULL
)

CREATE TABLE CommentLikes(
	CommentLikeID CHAR(20),
	CommentID CHAR(20),
	UserID CHAR(15) NOT NULL,
	
	CONSTRAINT CommentLikes_CommentLikeID_PK PRIMARY KEY(CommentLikeID),
	CONSTRAINT CommentLikes_CommentID_FK FOREIGN KEY(CommentID) REFERENCES Comments(CommentID) ON UPDATE CASCADE ON DELETE SET NULL
)